name: dotnet install reproduce error

on: 
 workflow_dispatch:

jobs:
  dotnet-install-error:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup .NET 8
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '8.0.x'

      - name: Use .NET 8
        run: dotnet --version

      # Install .NET 9
      - name: Setup .NET 9
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Use .NET 10
        run: dotnet --version
   
