name: Dotnet Install File Lock Reproduce Error

on: 
  workflow_dispatch:

jobs:
  dotnet-install-error:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      # This will launch a dotnet process that doesn't exit immediately!
      - name: Start a long-running dotnet process in background
        shell: pwsh
        run: |
          Start-Process -NoNewWindow -FilePath "dotnet" -ArgumentList "help"
          Start-Sleep -Seconds 30

      - name: Setup .NET 7 (should hit the lock issue)
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Use .NET 7
        run: dotnet --list-sdks
