name: Dotnet Install File Lock Reproduce Error

on: 
  workflow_dispatch:

jobs:
  dotnet-install-error:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: gowridurgad/setup-dotnet@testing-642
        with:
          dotnet-version: '8.0.x'

      - name: Restore packages 
        run: dotnet restore MyApp/MyApp.csproj 
      - name: Build
        run: dotnet build MyApp/MyApp.csproj
        
      - name: Setup .NET 9 (should hit the lock issue)
        uses: gowridurgad/setup-dotnet@testing-642
        with:
          dotnet-version: '9.0.x'
          
      - name: Restore packages
        run: dotnet restore MyApp/MyApp.csproj 
      - name: Build
        run: dotnet build MyApp/MyApp.csproj
        
