name: dotnet install reproduce error

on: 
 workflow_dispatch:

jobs:
  dotnet-install-error:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup .NET 8
        uses: gowridurgad/setup-dotnet@testing-642
        with:
          dotnet-version: '7.0.x'

      - name: Use .NET 8
        run: dotnet --version

    
      - name: Setup .NET 9
        uses: gowridurgad/setup-dotnet@testing-642
        with:
          dotnet-version: '6.0.x'

      - name: Use .NET 10
        run: dotnet --version
   
