name: testing688

on: 
  workflow_dispatch:

jobs:
  dotnet-install-error:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Add this diagnostic step
      - name: Print runner architecture before installing dotnet
        run: |
          echo "arch: $(arch)"
          uname -m

      - name: Clean old dotnet
        run: rm -rf ~/.dotnet

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'
         

      # Add another diagnostic step
      - name: Print dotnet info (after install)
        run: |
          dotnet --info
          echo "arch: $(arch)"
          uname -m

      - name: Build API
        run: dotnet build MyApp/MyApp.csproj
