name: workloads-523
on: 
  workflow_dispatch:

jobs:
  dotnet-install-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: gowridurgad/setup-dotnet@workload-input
        with:
          dotnet-version: '9.0.x'
          workloads: wasm-tools
          
      
      - name: Show installed workloads
        run: dotnet workload list
