name: testing677
on:
  workflow_dispatch:
jobs:
  setup:
    name: Setup .NET on all platforms
    runs-on: ubuntu-latest
  
    steps:
      - name: setup-dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '4.x'
