name: workloads-523
on: 
  workflow_dispatch:

jobs:
  dotnet-install-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: harithavattikuti/setup-dotnet@add-workloads-parameter
        with:
          dotnet-version: '8.0.x'
          workloads: maui
      
      - name: Show installed workloads
        run: dotnet workload list

      - name: Restore packages
        run: dotnet restore MyApp/MyApp.csproj

      - name: Build
        run: dotnet build MyApp/MyApp.csproj
