name: workloads-523
on: 
 workflow_dispatch:

jobs:
  dotnet-install-error:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup .NET 6
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '7.0.x'
          # workloads: maui, aspire

      - name: Show installed workloads
        run: dotnet workload list
