name: workloads-523
on: 
 workflow_dispatch:

jobs:
  dotnet-install-error:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Setup .NET 6
        uses: gowridurgad/setup-dotnet@workload-523
        with:
          dotnet-version: '9.0.x'
          workloads: |
                 maui
                 aspire

      - name: Show installed workloads
        run: dotnet workload list
