name: workloads-523
on: 
  workflow_dispatch:

jobs:
  dotnet-install-matrix:
    runs-on: self-hosted
    # strategy:
    #   matrix:
    #     os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: gowridurgad/setup-dotnet@workloads-input
        with:
          dotnet-version: '10.0.x'
          workloads: maui

      - name: Show .NET version
        run: dotnet --version
          
      
      - name: Show installed workloads
        run: dotnet workload list
