name: workloads-523
permissions:
  contents: write
  packages: write
on: 
  workflow_dispatch:

jobs:
  dotnet-install-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest]
        dotnet: [ '9.0.x' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v5    

      - name: Setup .NET 8
        uses: gowridurgad/setup-dotnet@523-feature
        # uses: actions/setup-dotnet@v5
        with:
         dotnet-version: ${{ matrix.dotnet }}
         workloads: wasm-tools   


      - name: Restore dependencies
        run: dotnet restore MyApp/MyApp.csproj

      - name: Build project
        run: dotnet build --configuration Release  MyApp/MyApp.csproj

      - name: Pack project
        run: dotnet pack --configuration Release --output ./nupkg MyApp/MyApp.csproj

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./nupkg/*.nupkg -s https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -k ${{ secrets.GITHUB_TOKEN }}
         
      
      # - name: Build
      #   run: dotnet build
      # - name: Create the package
      #   run: dotnet pack --configuration Release 
      # - name: Publish to GitHub Packages
      #   run: dotnet nuget push ./nupkg/*.nupkg -s https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -k ${{ secrets.GITHUB_TOKEN }}
