name: workloads-523
on: 
  workflow_dispatch:

jobs:
  dotnet-install-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        dotnet: [ '9.0.x' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v5    

      - name: Setup .NET 8
        uses: gowridurgad/setup-dotnet@523-feature
        # uses: actions/setup-dotnet@v5
        with:
         dotnet-version: ${{ matrix.dotnet }}
         workloads: wasm-tools   
         
         source-url: https://nuget.pkg.github.com/gowriduragd/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.TOKEN_GITHUB }}

      - name: Build
        run: dotnet build MyApp/MyApp.csproj
      - name: Create the package
        run: dotnet pack --configuration Release MyApp/MyApp.csproj
      - name: Publish the package to GPR
        run: dotnet nuget push  MyApp/bin/Release/*.nupkg


       

