name: workloads-523
on: 
  workflow_dispatch:

jobs:
  dotnet-install-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04-arm, windows-11-arm]
        dotnet: [ '9.0.x', '10.0.x']

    steps:
      - name: Checkout
        uses: actions/checkout@v5    

      - name: Setup .NET 8
        uses: gowridurgad/setup-dotnet@523-feature
        # uses: actions/setup-dotnet@v5
        with:
         dotnet-version: ${{ matrix.dotnet }}
         workloads: wasm-tools   
         
      - name: Show installed workloads
        run: dotnet workload list


       

