name: workloads-523
on: 
  workflow_dispatch:

jobs:
  dotnet-install-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Ensure NuGet cache directory exists
        run: mkdir -p /home/runner/.nuget/packages

      - name: Setup .NET 8
        uses: gowridurgad/setup-dotnet@523-feature
        # uses: actions/setup-dotnet@v5
        with:
         dotnet-version: 8.0.x
         workloads: wasm-tools
         cache: true
          
      
      - name: Show installed workloads
        run: dotnet workload list


       

